### ISSUE TITLE
Hook fails without global npm install

### ISSUE THREAD

**Issue by FatherShawn** [pre-commit/mirrors-eslint#10]
I have the following config:
```
- repo: git://github.com/pre-commit/mirrors-eslint
  sha: v4.11.0
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint-config-airbnb@14.1.0
    - eslint-plugin-import@2.2.0
    - eslint-plugin-jsx-a11y@4.0.0
    - eslint-plugin-react@6.10.3
    exclude: ^(... several patterns listed here)
    stages: [commit, push]
```
And I get:

```
pre-commit run -a eslint
eslint...................................................................Failed
hookid: eslint

Executable `eslint` not found
```
If I globally install eslint then it works but I would have to install the dependencies, and so would my team, which I believe misses the point??

OS: macOS 10.12.6
pre-commit: 1.1.2 installed via homebrew.

**Comment by asottile** [comment]
This repository uses [`additional_dependencies` to install `eslint` itself](https://github.com/pre-commit/mirrors-eslint/blob/f9fe3ef0a212c924b6cd55635907a2ed97b17164/.pre-commit-hooks.yaml#L8-L9) as there isn't a reliable way to ensure peer dependencies in most versions of node/npm.

This means that to continue to have `eslint` installed, you'll also want to list it in your overridden `additional_dependencies`, I agree it's slightly kludgey but so are mirror repositories 🤷‍♂️ (in an ideal world upstreams would provide the metadata, we're slowing getting to that place but there hasn't been a big push for that).

Another option is to use [`local` repositories](http://pre-commit.com/#repository-local-hooks) and avoid mirrors, they don't have as much of this problem but then you have to configure more yourself

Something like:

```yaml
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: eslint
        language: node
        files: \.js$
        additional_dependencies: [...]
```

**Comment by FatherShawn** [comment]
Thanks @asottile That did it - I feel like I should have thought of that!  Closing but leaving the following yaml snippet for other who find the issue, just to make it perfectly clear:

```
- repo: git://github.com/pre-commit/mirrors-eslint
  sha: v4.11.0
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint@3.19.0
    - eslint-config-airbnb@14.1.0
    - eslint-plugin-import@2.2.0
    - eslint-plugin-jsx-a11y@4.0.0
    - eslint-plugin-react@6.10.3
```
