### ISSUE TITLE
v5.x.x not picking up changed files

### ISSUE THREAD

**Issue by himynameisdave** [pre-commit/mirrors-eslint#14]
Having issues where precommit reports "no changed files" when I've staged js/jsx files (with linter errors). Here's the relevant part of the `pre-commit` file:

```yaml
-   repo: https://github.com/pre-commit/mirrors-eslint.git
    sha: v5.2.0
    hooks:
    -   id: eslint
        files: \.jsx?$
        additional_dependencies:
        - babel-eslint@8.2.6
        - babel-core@6.26.3
        - babel-plugin-module-resolver@3.1.1
        - eslint-config-7geese@0.1.0
        - eslint-import-resolver-babel-module@4.0.0
        - eslint-plugin-7g@1.0.0
        - eslint-plugin-compat@2.5.1
        - eslint-plugin-filenames@1.3.2
        - eslint-plugin-import@2.13.0
        - eslint-plugin-jest@21.18.0
        - eslint-plugin-promise@3.8.0
        - eslint-plugin-react@7.10.0
        - eslint@5.2.0
```

Seems to work if I just point the `sha` at any v4.19.x version, any idea what's going on here?
