### ISSUE TITLE
eslint passes locally, but doesn't pass on github

### ISSUE THREAD

**Issue by kulti** [pre-commit/mirrors-eslint#20]
Hi, I just migrate from tslint to eslint and try to configure my pre-commit hooks to use eslint.

Local running `pre-commit run --show-diff-on-failure --color=always --all-files` passes successful, but after pushing to github, a similar run fails with 108 errors.

I found that after deleting node_modules folder I have 56 errors after local running pre-commit. They look similar to 108 errors on github.

Please, help me understand the difference. I'm not familiar with javascript or typescript. I try to add some additional_dependencies but have no luck.

Example of failed job https://github.com/kulti/task-list/pull/96/checks?check_run_id=895492107.

**.pre-commit-config.yaml**
```
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: master
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint
          - typescript
          - typescript-eslint
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
```

**.eslintrc.js**
```
module.exports = {
  env: {
    browser: true,
    es6: true,
  },
  extends: [
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./front/tsconfig.eslint.json",
    sourceType: "module",
  },
  plugins: ["@typescript-eslint"],
  rules: {
    "@typescript-eslint/no-var-requires": 0,
  },
};
```

**tsconfig.eslint.json**
```
{
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts",
    "tests/**/*.ts",
    ".eslintrc.js",
    "jest.config.js",
    "webpack.config.js"
  ],
  "exclude": ["node_modules", "src/openapi_cli"]
}
```

**Comment by asottile** [comment]
my guess is that you're using (unsupported) [`rev: master`](https://pre-commit.com/#using-the-latest-version-for-a-repository)

though I'm not at a computer to better validate

**Comment by kulti** [comment]
Thank you for your suggestion. I have tried changing to v7.5.0, but it does not help.

**Comment by asottile** [comment]
weird, fwiw I get the output from CI locally

can you share your pre-commit version and `pre-commit run --all-files` locally?

**Comment by asottile** [comment]
you could also try running with `--verbose` in case there's something else locally interfering?

**Comment by kulti** [comment]
pre-commit version 2.6.0

Local output after deleting node_modules: https://pastebin.com/7Mxvu5cC.

Verbose flag just adds a hook id and duration to the output.

**Comment by kulti** [comment]
Maybe the problem in the workflow file?

pre-commit job:
```
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: set PY
        run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v2.0.0
```

I try to extend this job by `npm install`:
```
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
        working-directory: front
```
but that does not help too.
