### ISSUE TITLE
Does not add/user dependencies with @ prefix

### ISSUE THREAD

**Issue by jjorissen52** [pre-commit/mirrors-eslint#22]
I have added the below config to my `.pre-commit-config.yaml` file:

```yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: master
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@4.15.0
          - eslint-loader@4.0.2
          - eslint-plugin-react@7.21.5
          - eslint-plugin-react-hooks@4.0.0
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jsx-a11y@6.4.1
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - babel-eslint@10.1.0
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
```

Running `pre-commit`, I see the below. I believe it's because the plugin names begin with `@`. I had to try escaping with quotes as you can see because the leading `@` seemed to be invalid.

```
eslint...................................................................Failed
- hook id: eslint
- exit code: 1

Oops! Something went wrong! :(

ESLint: 4.15.0.
ESLint couldn't find the plugin "eslint-plugin-@typescript-eslint". This can happen for a couple 
different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-@typescript-eslint is also installed globally. 
A globally-installed ESLint cannot find a locally-installed plugin.
```

Any help would be appreciated!
