### ISSUE TITLE
Unable to resolve path to module in subdirectory

### ISSUE THREAD

**Issue by ravisumit33** [pre-commit/mirrors-eslint#23]
Pre-commit is unable to resolve paths for modules in subdirectory
My project directory structure is:
```
├── frontend
│   └── .eslintrc.json
│   └── node_modules
|   └── src
│   └── package.json
├── backend
│   └── requirements.txt
|    └── .pre-commit-config.yaml
├── .git
├── README.md
```

My `.eslintrc.json` is:
```json
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "airbnb",
        "prettier",
        "prettier/react",
        "react-app"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module",
        "parser": "babel-eslint"
    },
    "plugins": [
        "react",
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "error",
        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
    },
    "settings": {
        "react": {
            "version": "16.14.0"
        },
        "import/resolver": {
            "node": {
                "paths": ["./src"]
            }
        }
    }
}
```
My `.pre-commit-config.yaml` is:
```yaml
repos:
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.12.0
    hooks:
    -    id: eslint
         verbose: true
         args: ["--max-warnings=0", "--ignore-path", ".gitignore", "--rule", "no-console: 0"]
```

When I run `pre-commit run --all-files eslint`, I get many `unable to resolve path to module` errors for the modules located in `frontend/src`. There are no such errors when I go to `frontend` directory and run `eslint` on terminal. What can be the possible causes?
