### ISSUE TITLE
How to add additional_dependencies from private repositories

### ISSUE THREAD

**Issue by glensc** [pre-commit/mirrors-eslint#35]

**Comment by glensc** [comment]
@asottile so, describe how you add a private npm registry?

`eslint-config-mypackage` is in registry.private.org:

```yml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
        files: \.ts$
        types: [file]
        additional_dependencies:
          - eslint-config-mypackage@^4.4.0
```
