### ISSUE TITLE
Running eslint pre-commit with React

### ISSUE THREAD

**Issue by talmaj-at-hypothetic** [pre-commit/mirrors-eslint#36]
I have tried multiple things but I always get the following error:
```
40:4  error  Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (40:4)
```
 I have the following settings in .eslintrc:
 ```
 {
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier"
  ],
  "parser": "@babel/eslint-parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "requireConfigFile": false,
    "sourceType": "module"
  },
  "plugins": ["prefer-arrow", "react", "import", "react-hooks", "jest"],
  "ignorePatterns": ["node_modules/"],
  "env": {
    "browser": true,
    "jest": true,
    "es6": true
  },
  "settings": {
    "react": {
      "version": "detect" // "detect" automatically picks the version you have installed.
    }
  },
  "overrides": [
    {
      "files": ["*.jsx", "*.js"]
    }
  ],
  "rules": {
    "prefer-arrow-callback": ["error", { "allowNamedFunctions": true }],
    "func-style": ["error", "expression", { "allowArrowFunctions": true }],
    "prefer-const": [
      "error",
      {
        "destructuring": "any",
        "ignoreReadBeforeAssign": false
      }
    ],
    "no-var": ["error"],
    "react/prop-types": ["off"],
    "max-len": ["error", { "code": 88, "tabWidth": 4 }],
    "keyword-spacing": ["error"],
    "space-before-blocks": ["error"],
    "prefer-template": ["error"],
    "no-useless-concat": ["error"],
    "quotes": ["error", "double"],
    "camelcase": [
      "error", {
        "properties": "never"
      }]
  }
}
 ```
 and the following .pre-commit-config.yaml
 ```
 repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--target-version, py310]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=./backend/.flake8]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.16.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args:
          [
            --config=frontend/.eslintrc,
            --ignore-path=frontend/.eslintignore,
            --fix,
          ]
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-plugin-flow
          - eslint-plugin-import
          - eslint-plugin-jest
          - eslint-plugin-prefer-arrow
          - eslint-plugin-react
          - eslint-plugin-react-hooks

 ```
 Any help would be appreciated.
