### ISSUE TITLE
pre-commit outputs same error multiple times

### ISSUE THREAD

**Issue by BeyondEvil** [pre-commit/mirrors-eslint#39]
Running `npm run lint` produces:

```
❯ npm run lint

> lint
> eslint src/pytest_html/scripts


/Users/jimbrannlund/dev/pytest/pytest-html/src/pytest_html/scripts/dom.js
  93:33  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)
```

Running `pre-commit --all-files eslint` produces:

```
❯ pre-commit run --all-files eslint
eslint...................................................................Failed
- hook id: eslint
- exit code: 1


/Users/jimbrannlund/dev/pytest/pytest-html/src/pytest_html/scripts/dom.js
  93:33  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)


/Users/jimbrannlund/dev/pytest/pytest-html/src/pytest_html/scripts/dom.js
  93:33  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)


/Users/jimbrannlund/dev/pytest/pytest-html/src/pytest_html/scripts/dom.js
  93:33  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)
```

Relevant parts of `package.json`:

```json
{
  "scripts": {
    "lint": "eslint src/pytest_html/scripts"
  },
  "devDependencies": {
    "eslint": "^8.20.0",
    "eslint-config-google": "^0.14.0"
  }
}
```

Relevant parts of `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.20.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.20.0
          - eslint-config-google@0.14.0
        args: ["src/pytest_html/scripts"]
```

Environment:

```
❯ pre-commit --version             
pre-commit 3.2.2
```

```
❯ python --version             
Python 3.9.10
```

```
❯ uname -a           
Darwin beyondevil.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
```

Am I doing something wrong?
