### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-react". 

### ISSUE THREAD

**Issue by clickstefan** [pre-commit/mirrors-eslint#6]
this is my `.pre-commit-config.yaml`

```
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: '3f5585a65eeec878e779a5630628db158ba3dab1'  # Use the sha you want to point at
    hooks:
    -   id: eslint
```

my `.eslintrc.yml`

```
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
```

And this is what I get on commit

```
git commit -a -m 'initial commit'
eslint....................................................................................................................................................................................Failed
hookid: eslint

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Locally it runs fine (`node ./node_modules/eslint/bin/eslint.js`).

Tried to install eslint globally with all plugins but still get the same error. 

Where does pre-commit install the plugins ? I'm guessing running `npm i eslint-plugin-react@latest --save-dev` there should fix it.

**Comment by asottile** [comment]
pre-commit creates an isolated environment for each hook to ensure reproducibility.  If you'd like to install additional things alongside the hook executables the `additional_dependencies` setting allows you to do that.  For more information on that, check out http://pre-commit.com

I beleive for eslint + eslint-react you'd do something like:

```yaml
-   repo: https://github.com/pre-commit/mirrors-eslint
    sha: 3.7.0
    hooks:
    -    id: eslint
        # Admittedly, a little strange because of the way the npm "mirror" repos work
        additional_dependencies: ['eslint@3.7.0', 'eslint-plugin-react']
```
